[project]
name = "hearmypaper-client"
version = "0.1.0"
description = "HearMyPaper client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "briefcase>=0.3.25",
    "cryptography>=46.0.1",
    "requests>=2.32.5",
    "ruff>=0.13.0",
]
