s1: III рівень конфіденційності {
  grid-rows: 2

  admin: Адміністратор
  admin.shape: oval

  s2: II рівень конфіденційності {
    grid-rows: 2

    instructor: Викладач
    instructor.shape: oval

    s3: I рівень конфіденційності {
      grid-rows: 2

      student: Студент
      student.shape: oval

      curator: Куратор
      curator.shape: oval
    }
  }
}

o1: III рівень конфіденційності {
  grid-rows: 2

  user_info: Інформація про користувача
  user_info.shape: oval

  o2: II рівень конфіденційності {
    grid-rows: 2

    project_content: Контент проекту
    project_content.shape: oval

    o3: I рівень конфіденційності {
      grid-rows: 2

      project_info: Інформація про проект
      project_info.shape: oval
    }
  }
}

s1.admin -> o1.user_info
s1.admin -> o1.o2.project_content
s1.admin -> o1.o2.o3.project_info

s1.s2.instructor -> o1.o2.project_content
s1.s2.instructor -> o1.o2.o3.project_info

s1.s2.s3.curator -> o1.o2.o3.project_info

s1.s2.s3.student -> o1.o2.o3.project_info

